### ISSUE TITLE
Error occurs when pressing the + button instead of dragging after page build (at the very first time)

### ISSUE THREAD

**Issue by dvlj** [wiltonribeiro/menu_tabbar_flutter#1]
When i press the + button, error occur as follow, any help?:

flutter: #3      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:765
flutter: #4      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:228
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1012
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:928
flutter: #7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:367:8)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame 
package:flutter/…/scheduler/binding.dart:926
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame 
package:flutter/…/scheduler/binding.dart:856
flutter: #13     _invoke1  (dart:ui/hooks.dart:250:10)
flutter: #14     _beginFrame  (dart:ui/hooks.dart:177:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The AnimationController notifying listeners was:
flutter:   AnimationController#b667e(▶ 0.000)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'value' was called on null.
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'addListener' was called on null.
Receiver: null
Tried calling: addListener(Closure: () => Null)
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
#1      _MenuTabBar._moveButtonDown.<anonymous closure> 
package:menu_tabbar/components/menu_tab_bar.dart:137
#2      _rootRun  (dart:async/zone.dart:1120:38)
#3      _CustomZone.run  (dart:async/zone.dart:1021:19)
#4      _FutureListener.handleWhenComplete  (dart:async/future_impl.dart:150:18)
#5      Future._propagateToListeners.handleWhenCompleteCallback  (dart:async/future_impl.dart:609:39)
#6      Future._propagateToListeners  (dart:async/future_impl.dart:665:37)
#7      Future._completeWithValue  (dart:async/future_impl.dart:483:5)
#8      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
#9      _rootRun  (dart:async/zone.dart:1124:13)
#10     _CustomZone.run  (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (d<…>
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'addListener' was called on null.
Receiver: null
Tried calling: addListener(Closure: () => Null)
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
#1      _MenuTabBar._moveButtonUp.<anonymous closure> 
package:menu_tabbar/components/menu_tab_bar.dart:148
#2      _rootRun  (dart:async/zone.dart:1120:38)
#3      _CustomZone.run  (dart:async/zone.dart:1021:19)
#4      _FutureListener.handleWhenComplete  (dart:async/future_impl.dart:150:18)
#5      Future._propagateToListeners.handleWhenCompleteCallback  (dart:async/future_impl.dart:609:39)
#6      Future._propagateToListeners  (dart:async/future_impl.dart:665:37)
#7      Future._completeWithValue  (dart:async/future_impl.dart:483:5)
#8      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
#9      _rootRun  (dart:async/zone.dart:1124:13)
#10     _CustomZone.run  (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dar<…>

**Comment by thundertrick** [comment]
It can be fixed by adding `_updateButtonPosition` when click + button.

**Comment by dvlj** [comment]
Thanks, I will try this later and come back to you!

**Comment by dvlj** [comment]
it seems not a completely fix, the dragging animation (ripple) is disappeared when press +, button just jump out suddenly

**Comment by thundertrick** [comment]
> it seems not a completely fix, the dragging animation (ripple) is disappeared when press +, button just jump out suddenly

@dvlj 

Yes, this is the minimum fix I found.
If u wanna the animation back, just pass a valid `dy` to `_updateButtonPosition`.
For example
```dart
//... MenuTabBar.dart
onPressed: (){
  _updateButtonPosition(MediaQuery.of(context).size.height);
  if(_isActivated.stream.value == 1) {
    _moveButtonDown();
  } else {
    _moveButtonUp();
  }
}
//...
```

**Comment by dvlj** [comment]
got it!  thanks for the update! closing now
